### ISSUE TITLE
Instalarte Pycharm y Jupyter notebooks

### ISSUE THREAD

**Issue by g-revilla** [danipoal/python#1]
Para empezar con Python, te recomiendo instalarte Pycharm (entorno Anaconda), así como las las Jupyter notebooks.

Pycharm viene muy bien para desarrollar código, sobretodo su Debug, y su vínculo directo con Git.

Jupyter está muy bien para docuementar, así como para hacer diferentes ejercicios o entregas, combinándolo con texto escrito.

**Comment by danipoal** [comment]
Perfecto, gracias @g-revilla :)
